## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,4,Avarua,CK,73.40,overcast clouds,-21.21,-159.78,Paradise Inn
1,5,Karratha,AU,70.32,few clouds,-20.74,116.85,ibis Styles Karratha
2,9,Rikitea,PF,73.54,scattered clouds,-23.12,-134.97,Pension Maro'i
3,17,Dingle,PH,76.60,clear sky,11.00,122.67,Camp Pasica
4,25,Gat,IL,78.01,clear sky,31.61,34.76,OlusHome
...,...,...,...,...,...,...,...,...
130,628,Baringo,KE,79.41,light rain,0.47,35.97,Jericho Lodging
131,631,Weatherford,US,77.00,few clouds,32.76,-97.80,Candlewood Suites Weatherford
132,638,Jabinyanah,TN,75.20,clear sky,35.03,10.91,maison belmabrouk
133,651,Danville,US,79.00,clear sky,36.59,-79.39,Holiday Inn Express Danville
134,656,Gambo,CF,75.45,overcast clouds,4.65,22.26,NaN

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 30.0), zoom_level=1.7)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Karratha"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Karratha"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Maningrida"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Mount Isa"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Yulara"] 
vacation_start

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,5,Karratha,AU,70.32,few clouds,-20.74,116.85,ibis Styles Karratha

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [7]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
directions_layer = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3])
fig.add_layer(directions_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_end, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,5,Karratha,AU,70.32,few clouds,-20.74,116.85,ibis Styles Karratha
1,5,Karratha,AU,70.32,few clouds,-20.74,116.85,ibis Styles Karratha
2,615,Maningrida,AU,79.05,broken clouds,-12.07,134.27,Dhukurrdji Lodge
3,191,Mount Isa,AU,77.00,broken clouds,-20.73,139.50,ibis Styles Mt Isa Verona
4,151,Yulara,AU,78.80,clear sky,-25.24,130.99,Desert Gardens Hotel - Ayers Rock Resort

In [9]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [10]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))